# Generated by Django 5.2.4 on 2025-08-20 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supplier', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='static/media')),
                ('expiry_date', models.DateField()),
                ('category', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('recorded_date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
